/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.autoboss.view;

import br.inatel.autoboss.contoller.ProjetoDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Joao Leonardo
 */
public class Buscar extends javax.swing.JFrame {

    int usuarioId;
    
    public Buscar() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        jTextField1.setBackground(new Color(0, 0, 0, 200));        
    }

    public Buscar(int usuario) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        jTextField1.setBackground(new Color(0, 0, 0, 200)); 
        usuarioId = usuario;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jDesMulti = new javax.swing.JButton();
        jWebApps = new javax.swing.JButton();
        jSoftSistem = new javax.swing.JButton();
        jEngenManu = new javax.swing.JButton();
        jMarkVend = new javax.swing.JButton();
        jGestConsult = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 540));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesMulti.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jDesMulti.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jDesMulti.setForeground(new java.awt.Color(153, 153, 153));
        jDesMulti.setText("DESIGN E MULTIMEDIA");
        jDesMulti.setBorder(null);
        jDesMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDesMultiActionPerformed(evt);
            }
        });
        jPanel2.add(jDesMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 250, 70));

        jWebApps.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jWebApps.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jWebApps.setForeground(new java.awt.Color(153, 153, 153));
        jWebApps.setText("WEBSITES E APPS");
        jWebApps.setBorder(null);
        jWebApps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWebAppsActionPerformed(evt);
            }
        });
        jPanel2.add(jWebApps, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 250, 70));

        jSoftSistem.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jSoftSistem.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jSoftSistem.setForeground(new java.awt.Color(153, 153, 153));
        jSoftSistem.setText("SOFTWARES E SISTEMAS");
        jSoftSistem.setBorder(null);
        jSoftSistem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSoftSistemActionPerformed(evt);
            }
        });
        jPanel2.add(jSoftSistem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 250, 70));

        jEngenManu.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jEngenManu.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jEngenManu.setForeground(new java.awt.Color(153, 153, 153));
        jEngenManu.setText("ENGENHARIA E MANUFATURA");
        jEngenManu.setBorder(null);
        jEngenManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEngenManuActionPerformed(evt);
            }
        });
        jPanel2.add(jEngenManu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 250, 70));

        jMarkVend.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jMarkVend.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jMarkVend.setForeground(new java.awt.Color(153, 153, 153));
        jMarkVend.setText("MARKETING E VENDAS");
        jMarkVend.setBorder(null);
        jMarkVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMarkVendActionPerformed(evt);
            }
        });
        jPanel2.add(jMarkVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 250, 70));

        jGestConsult.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jGestConsult.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jGestConsult.setForeground(new java.awt.Color(153, 153, 153));
        jGestConsult.setText("GESTÃO E CONSULTORIA");
        jGestConsult.setBorder(null);
        jGestConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGestConsultActionPerformed(evt);
            }
        });
        jPanel2.add(jGestConsult, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 250, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1080, 540));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("BUSCAR PROJETOS");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jTextField1.setPreferredSize(new java.awt.Dimension(1082, 186));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1090, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buscar_projetos.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1080, 184));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 25));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(200, 30));

        jMenu3.setBackground(new java.awt.Color(51, 51, 51));
        jMenu3.setText("PERFIL");
        jMenu3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(95, 25));
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(51, 51, 51));
        jMenu4.setBorder(null);
        jMenu4.setText("PROJETOS");
        jMenu4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenu4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(95, 25));

        jMenuItem1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem1.setText("FREELANCER");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(115, 25));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem2.setText("CLIENTE");
        jMenuItem2.setPreferredSize(new java.awt.Dimension(115, 25));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu2.setBackground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("CRIAR");
        jMenu2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(95, 25));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("BUSCAR");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(95, 25));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu5.setBackground(new java.awt.Color(51, 51, 51));
        jMenu5.setText("SAIR");
        jMenu5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(95, 25));
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jWebAppsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWebAppsActionPerformed
       
        //variaveis
        String categoria = "WebSites e Apps";
        boolean vazio;
        
        //objeto ProjetoDao
        ProjetoDAO projDAO = new ProjetoDAO();
        
        //retorna se ha algum projeto cadastrado
        vazio = projDAO.retornaSeTemProjetoPelaCategoria(categoria);
        
        if(vazio){
            JOptionPane.showMessageDialog(null, "Não há projetos cadastrados nessa categoria!!");
        }
        else{
            ProjetosBuscados projetosBuscados = new ProjetosBuscados(usuarioId, categoria);
            projetosBuscados.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jWebAppsActionPerformed

    private void jEngenManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEngenManuActionPerformed
        //variaveis
        String categoria = "Engenharia e Manufatura";
        boolean vazio;
        
        //objeto ProjetoDao
        ProjetoDAO projDAO = new ProjetoDAO();
        
        //retorna se ha algum projeto cadastrado
        vazio = projDAO.retornaSeTemProjetoPelaCategoria(categoria);
        
        if(vazio){
            JOptionPane.showMessageDialog(null, "Não há projetos cadastrados nessa categoria!!");
        }
        else{
            ProjetosBuscados projetosBuscados = new ProjetosBuscados(usuarioId, categoria);
            projetosBuscados.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jEngenManuActionPerformed

    private void jGestConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGestConsultActionPerformed
        //variaveis
        String categoria = "Gestão e Consultoria";
        boolean vazio;
        
        //objeto ProjetoDao
        ProjetoDAO projDAO = new ProjetoDAO();
        
        //retorna se ha algum projeto cadastrado
        vazio = projDAO.retornaSeTemProjetoPelaCategoria(categoria);
        
        if(vazio){
            JOptionPane.showMessageDialog(null, "Não há projetos cadastrados nessa categoria!!");
        }
        else{
            ProjetosBuscados projetosBuscados = new ProjetosBuscados(usuarioId, categoria);
            projetosBuscados.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jGestConsultActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        Perfil perfil = new Perfil(usuarioId);
        perfil.setVisible(true);
        dispose();   
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ProjetosFreela projetosFreela = new ProjetosFreela(usuarioId);
        projetosFreela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ProjetosCliente projetosCliente = new ProjetosCliente(usuarioId);
        projetosCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Criar criar = new Criar(usuarioId);
        criar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Buscar buscar = new Buscar(usuarioId);
        buscar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jDesMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDesMultiActionPerformed
        //variaveis
        String categoria = "Desing e Multimedia";
        boolean vazio;
        
        //objeto ProjetoDao
        ProjetoDAO projDAO = new ProjetoDAO();
        
        //retorna se ha algum projeto cadastrado
        vazio = projDAO.retornaSeTemProjetoPelaCategoria(categoria);
        
        if(vazio){
            JOptionPane.showMessageDialog(null, "Não há projetos cadastrados nessa categoria!!");
        }
        else{
            ProjetosBuscados projetosBuscados = new ProjetosBuscados(usuarioId, categoria);
            projetosBuscados.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jDesMultiActionPerformed

    private void jMarkVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMarkVendActionPerformed
        //variaveis
        String categoria = "Marketing e Vendas";
        boolean vazio;
        
        //objeto ProjetoDao
        ProjetoDAO projDAO = new ProjetoDAO();
        
        //retorna se ha algum projeto cadastrado
        vazio = projDAO.retornaSeTemProjetoPelaCategoria(categoria);
        
        if(vazio){
            JOptionPane.showMessageDialog(null, "Não há projetos cadastrados nessa categoria!!");
        }
        else{
            ProjetosBuscados projetosBuscados = new ProjetosBuscados(usuarioId, categoria);
            projetosBuscados.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jMarkVendActionPerformed

    private void jSoftSistemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSoftSistemActionPerformed
        //variaveis
        String categoria = "Softwares e Sistemas";
        boolean vazio;
        
        //objeto ProjetoDao
        ProjetoDAO projDAO = new ProjetoDAO();
        
        //retorna se ha algum projeto cadastrado
        vazio = projDAO.retornaSeTemProjetoPelaCategoria(categoria);
        
        if(vazio){
            JOptionPane.showMessageDialog(null, "Não há projetos cadastrados nessa categoria!!");
        }
        else{
            ProjetosBuscados projetosBuscados = new ProjetosBuscados(usuarioId, categoria);
            projetosBuscados.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jSoftSistemActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDesMulti;
    private javax.swing.JButton jEngenManu;
    private javax.swing.JButton jGestConsult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jMarkVend;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jSoftSistem;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jWebApps;
    // End of variables declaration//GEN-END:variables
}
