/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.autoboss.view;

import br.inatel.autoboss.model.UsuarioGeral;
import br.inatel.autoboss.contoller.UsuarioGeralDAO;
import br.inatel.autoboss.model.UsuarioHasConhecimento;
import br.inatel.autoboss.contoller.UsuarioHasConhecimentoDAO;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Joao Leonardo
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Cadastrar() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        jTextField1.setBackground(new Color(0, 0, 0, 200));
    }

    //variaveis de armazenamento dos dados
    private String nome;
    private String email;
    private int cnpj;
    private int cpf;
    private String senha;
    private int telefone;
    private String imagem = "/assets/imagem_perfil.png";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jNomeText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jJava = new javax.swing.JCheckBox();
        jRedes = new javax.swing.JCheckBox();
        jHTML = new javax.swing.JCheckBox();
        jSwift = new javax.swing.JCheckBox();
        jPython = new javax.swing.JCheckBox();
        jJS = new javax.swing.JCheckBox();
        jPHP = new javax.swing.JCheckBox();
        jAG = new javax.swing.JCheckBox();
        jSolucao = new javax.swing.JCheckBox();
        jCalculos = new javax.swing.JCheckBox();
        jGestao = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jEmailText = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jFoto = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jCelText = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComunicacao = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jCpfText = new javax.swing.JTextField();
        jCnpjText = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jCnpjBtn = new javax.swing.JRadioButton();
        jCpfBtn = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 540));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 480, -1));

        jNomeText.setBackground(new java.awt.Color(51, 51, 51));
        jNomeText.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jNomeText.setForeground(new java.awt.Color(255, 255, 255));
        jNomeText.setBorder(null);
        jNomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeTextActionPerformed(evt);
            }
        });
        jPanel2.add(jNomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 480, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("HABILIDADE:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jJava.setBackground(new java.awt.Color(51, 51, 51));
        jJava.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jJava.setForeground(new java.awt.Color(153, 153, 153));
        jJava.setText("JAVA");
        jPanel2.add(jJava, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jRedes.setBackground(new java.awt.Color(51, 51, 51));
        jRedes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jRedes.setForeground(new java.awt.Color(153, 153, 153));
        jRedes.setText("REDES");
        jPanel2.add(jRedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        jHTML.setBackground(new java.awt.Color(51, 51, 51));
        jHTML.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jHTML.setForeground(new java.awt.Color(153, 153, 153));
        jHTML.setText("HTML");
        jHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHTMLActionPerformed(evt);
            }
        });
        jPanel2.add(jHTML, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jSwift.setBackground(new java.awt.Color(51, 51, 51));
        jSwift.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jSwift.setForeground(new java.awt.Color(153, 153, 153));
        jSwift.setText("SWIFT");
        jPanel2.add(jSwift, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jPython.setBackground(new java.awt.Color(51, 51, 51));
        jPython.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPython.setForeground(new java.awt.Color(153, 153, 153));
        jPython.setText("PYTHON");
        jPanel2.add(jPython, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jJS.setBackground(new java.awt.Color(51, 51, 51));
        jJS.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jJS.setForeground(new java.awt.Color(153, 153, 153));
        jJS.setText("JAVASCRIPT");
        jPanel2.add(jJS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jPHP.setBackground(new java.awt.Color(51, 51, 51));
        jPHP.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPHP.setForeground(new java.awt.Color(153, 153, 153));
        jPHP.setText("PHP");
        jPHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPHPActionPerformed(evt);
            }
        });
        jPanel2.add(jPHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jAG.setBackground(new java.awt.Color(51, 51, 51));
        jAG.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jAG.setForeground(new java.awt.Color(153, 153, 153));
        jAG.setText("ARTES GRÁFICAS");
        jAG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAGActionPerformed(evt);
            }
        });
        jPanel2.add(jAG, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jSolucao.setBackground(new java.awt.Color(51, 51, 51));
        jSolucao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jSolucao.setForeground(new java.awt.Color(153, 153, 153));
        jSolucao.setText("SOLUÇÕES");
        jSolucao.setToolTipText("");
        jPanel2.add(jSolucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jCalculos.setBackground(new java.awt.Color(51, 51, 51));
        jCalculos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCalculos.setForeground(new java.awt.Color(153, 153, 153));
        jCalculos.setText("CÁLCULOS");
        jCalculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalculosActionPerformed(evt);
            }
        });
        jPanel2.add(jCalculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jGestao.setBackground(new java.awt.Color(51, 51, 51));
        jGestao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jGestao.setForeground(new java.awt.Color(153, 153, 153));
        jGestao.setText("GESTÃO");
        jPanel2.add(jGestao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("CADASTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 383, 310, 50));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("E-MAIL:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 480, -1));

        jEmailText.setBackground(new java.awt.Color(51, 51, 51));
        jEmailText.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jEmailText.setForeground(new java.awt.Color(255, 255, 255));
        jEmailText.setBorder(null);
        jEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailTextActionPerformed(evt);
            }
        });
        jPanel2.add(jEmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 480, 20));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 480, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("CNPJ:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("SENHA:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 230, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("NOME:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jFoto.setBackground(new java.awt.Color(204, 0, 153));
        jFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagem_perfil.png"))); // NOI18N
        jPanel2.add(jFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 120, 170));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("CELULAR:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 230, 10));

        jCelText.setBackground(new java.awt.Color(51, 51, 51));
        jCelText.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCelText.setForeground(new java.awt.Color(255, 255, 255));
        jCelText.setBorder(null);
        jPanel2.add(jCelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 230, 20));

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 480, 20));

        jComunicacao.setBackground(new java.awt.Color(51, 51, 51));
        jComunicacao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComunicacao.setForeground(new java.awt.Color(153, 153, 153));
        jComunicacao.setText("COMUNICAÇÃO");
        jPanel2.add(jComunicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("CPF:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        jCpfText.setEditable(false);
        jCpfText.setBackground(new java.awt.Color(51, 51, 51));
        jCpfText.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCpfText.setForeground(new java.awt.Color(255, 255, 255));
        jCpfText.setBorder(null);
        jPanel2.add(jCpfText, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 230, 20));

        jCnpjText.setEditable(false);
        jCnpjText.setBackground(new java.awt.Color(51, 51, 51));
        jCnpjText.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCnpjText.setForeground(new java.awt.Color(255, 255, 255));
        jCnpjText.setBorder(null);
        jPanel2.add(jCnpjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 230, 20));

        jSeparator8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 230, 10));

        jCnpjBtn.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jCnpjBtn);
        jCnpjBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCnpjBtnMouseClicked(evt);
            }
        });
        jPanel2.add(jCnpjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 160, -1, -1));

        jCpfBtn.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jCpfBtn);
        jCpfBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCpfBtnMouseClicked(evt);
            }
        });
        jPanel2.add(jCpfBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, -1, -1));

        jButton2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setText("TROCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1070, 540));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("CADASTRO");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jTextField1.setPreferredSize(new java.awt.Dimension(1082, 186));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1090, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cadastrar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jNomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeTextActionPerformed

    private void jEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailTextActionPerformed

    private void jHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHTMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHTMLActionPerformed

    private void jCalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCalculosActionPerformed

    private void jPHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPHPActionPerformed

    private void jAGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAGActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Pegando oq esta escrito
        nome = jNomeText.getText();
        email = jEmailText.getText();
        senha = String.valueOf(jPasswordField1.getPassword());
        //tratamento de erros para telefone
        try {
            telefone = Integer.parseInt(jCelText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Entre com números para o celular!");
        }
        

        if (jCnpjBtn.isSelected()) {
            //tratamento de erros para cnpj
            try {
                cnpj = Integer.parseInt(jCnpjText.getText());
                jCpfText.setEditable(false);
                cpf = 0;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Entre com números para o cnpj!");
            }
            
        } else {
            //tratamento de erros para cpf
            try {
                cpf = Integer.parseInt(jCpfText.getText());
                cnpj = 0;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Entre com números para o cpf!");
            }
            
        }

        if (nome == "" || email == "" || senha == "" || telefone ==0 || imagem == "/assets/imagem_perfil.png" || (cpf == 0 && cnpj == 0)
                || (!jPHP.isSelected() && !jHTML.isSelected() && !jJava.isSelected() && !jSwift.isSelected() && !jPython.isSelected() && !jJS.isSelected()
                && !jComunicacao.isSelected() && !jAG.isSelected() && !jSolucao.isSelected() && !jCalculos.isSelected() && !jGestao.isSelected())) {
            JOptionPane.showMessageDialog(null, "Cadastre todos os itens corretamente!!");
        } else {
            //convertendo pra string 
            String tel = Integer.toString(telefone);
            String cp = Integer.toString(cpf);
            String cpj = Integer.toString(cnpj);
            //criando um objeto usuarioGeral
            UsuarioGeral u1 = new UsuarioGeral(nome, email, cp, cpj, senha, tel, imagem);

            //criando um objeto usuarioGeralDAO
            UsuarioGeralDAO udao = new UsuarioGeralDAO();

            //cadastrrando o usuario no bd
            udao.inserirUsuario(u1);

            //variavel id do usuario cadastrado
            int idUsuario = udao.retornaId(email);

            //ArrayList de conhecimentos
            List<Integer> conhecimentos = new ArrayList<>();

            //Preenchendo Conhecimentos
            if (jPHP.isSelected()) {
                conhecimentos.add(1);
            }
            if (jHTML.isSelected()) {
                conhecimentos.add(2);
            }
            if (jJava.isSelected()) {
                conhecimentos.add(3);
            }
            if (jSwift.isSelected()) {
                conhecimentos.add(4);
            }
            if (jPython.isSelected()) {
                conhecimentos.add(5);
            }
            if (jJS.isSelected()) {
                conhecimentos.add(6);
            }
            if (jComunicacao.isSelected()) {
                conhecimentos.add(7);
            }
            if (jAG.isSelected()) {
                conhecimentos.add(8);
            }
            if (jSolucao.isSelected()) {
                conhecimentos.add(9);
            }
            if (jCalculos.isSelected()) {
                conhecimentos.add(10);
            }
            if (jGestao.isSelected()) {
                conhecimentos.add(11);
            }
            if (jRedes.isSelected()) {
                conhecimentos.add(12);
            }

            //objteto UsuarioHasConhecimento
            UsuarioHasConhecimento uhc = new UsuarioHasConhecimento(idUsuario, 0);

            //objeto UsuarioHasConhecimentoDao
            UsuarioHasConhecimentoDAO uhcdao = new UsuarioHasConhecimentoDAO();

            for (int i = 0; i < conhecimentos.size(); i++) {
                //seta o id do conhecimento que esta guardado no arrayList
                uhc.setId_conhecimento(conhecimentos.get(i));

                //realiza a introdução no banco de dados
                uhcdao.inserirUsuarioHasConhecimento(uhc);
            }
            JOptionPane.showMessageDialog(null, "Cadastro realizado com Sucesso!!");
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCpfBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCpfBtnMouseClicked
        jCnpjText.setText("");
        jCnpjText.setEditable(false);
        jCpfText.setEditable(true);
    }//GEN-LAST:event_jCpfBtnMouseClicked

    private void jCnpjBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCnpjBtnMouseClicked
        jCpfText.setText("");
        jCnpjText.setEditable(true);
        jCpfText.setEditable(false);
    }//GEN-LAST:event_jCnpjBtnMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagens", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            imagem = selectedFile.getAbsolutePath();
            jFoto.setIcon(ResizeImage(imagem));
        } //if the user click on save in Jfilechooser
        else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jAG;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCalculos;
    private javax.swing.JTextField jCelText;
    private javax.swing.JRadioButton jCnpjBtn;
    private javax.swing.JTextField jCnpjText;
    private javax.swing.JCheckBox jComunicacao;
    private javax.swing.JRadioButton jCpfBtn;
    private javax.swing.JTextField jCpfText;
    private javax.swing.JTextField jEmailText;
    private javax.swing.JLabel jFoto;
    private javax.swing.JCheckBox jGestao;
    private javax.swing.JCheckBox jHTML;
    private javax.swing.JCheckBox jJS;
    private javax.swing.JCheckBox jJava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNomeText;
    private javax.swing.JCheckBox jPHP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JCheckBox jPython;
    private javax.swing.JCheckBox jRedes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JCheckBox jSolucao;
    private javax.swing.JCheckBox jSwift;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jFoto.getWidth(), jFoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

}
