/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.autoboss.view;

import br.inatel.autoboss.contoller.ProjetoDAO;
import br.inatel.autoboss.model.Projetos;
import br.inatel.autoboss.model.Proposta;
import br.inatel.autoboss.contoller.PropostaDAO;
import br.inatel.autoboss.contoller.UsuarioGeralDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Joao Leonardo
 */
public class ProjetosFreela extends javax.swing.JFrame {

    int usuarioId;
    private List<Projetos> listaProj = new ArrayList<>();
    private String tam = "0";
    private int atual = 0;
    private List<Proposta> listaProp = new ArrayList<>();
    private String tamProp = "0";
    private int atualProp = 0;
    private int idProjeto;

    //Objeto projeto DAO
    ProjetoDAO projdao = new ProjetoDAO();
    //Objeto proposta DAO
    PropostaDAO propdao = new PropostaDAO();
    //objeto UsuarioGeralDAO
    UsuarioGeralDAO udao = new UsuarioGeralDAO();

    public ProjetosFreela() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        jTextField1.setBackground(new Color(0, 0, 0, 200));
    }

    public ProjetosFreela(int usuario) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        jTextField1.setBackground(new Color(0, 0, 0, 200));
        usuarioId = usuario;

        //TABELA PROJETOS        
        //Preenchendo a lista de projetos
        listaProj = projdao.retornaProjetosPeloIdFreelancer(usuarioId);

        //verificando se há projetos
        if(!listaProj.isEmpty()){
            //setando o tamanho
            tam = Integer.toString((listaProj.size()));
            
            //mostra na interface
            jNProjText.setText(tam);            
            jNomeProj.setText(listaProj.get(atual).getNomeProjeto());
            jDescricaoProj.setText(listaProj.get(atual).getDescricaoProjeto());
            jOrcamentoProj.setText("R$: "+listaProj.get(atual).getPrecoMax());
        }else{
            jNProjText.setText(tam);
        }

        //TABELA PROPOSTAS                 
        //Preenchendo a lista de propostas
        listaProp = propdao.retornaPropostasPeloIdFreela(usuarioId);

        //verificando se há propostas
        if(listaProp.isEmpty())
        {
            jNPropText.setText(tamProp);
        }else{
            //mostra na interface
            tamProp = Integer.toString((listaProp.size()));
            jNPropText.setText(tamProp);
            jNomeProp.setText(projdao.retornaNomePeloId(listaProp.get(atualProp).getIdProjeto()));
            jOrcamentoProp.setText("R$: "+listaProp.get(atualProp).getValorProposta());
            jDescricaoProp.setText(listaProp.get(atualProp).getPropostaRealizada());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jNomeProj = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jDescricaoProj = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jOrcamentoProp = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jNomeProp = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jDescricaoProp = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jOrcamentoProj = new javax.swing.JTextArea();
        jRemoverBtn = new javax.swing.JButton();
        jAntPropbtn = new javax.swing.JButton();
        jProxPropbtn = new javax.swing.JButton();
        jProxProjbtn = new javax.swing.JButton();
        jAntProjbtn = new javax.swing.JButton();
        jNProjText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jNPropText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPerfilPropBtn = new javax.swing.JButton();
        jPerfilProjBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 540));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("DESENVOLVIMENTO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 730, 10));

        jScrollPane2.setBorder(null);

        jNomeProj.setEditable(false);
        jNomeProj.setBackground(new java.awt.Color(51, 51, 51));
        jNomeProj.setColumns(20);
        jNomeProj.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jNomeProj.setForeground(new java.awt.Color(153, 153, 153));
        jNomeProj.setRows(5);
        jNomeProj.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID - NOME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        jScrollPane2.setViewportView(jNomeProj);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 300, 140));

        jScrollPane4.setBorder(null);

        jDescricaoProj.setEditable(false);
        jDescricaoProj.setBackground(new java.awt.Color(51, 51, 51));
        jDescricaoProj.setColumns(20);
        jDescricaoProj.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jDescricaoProj.setForeground(new java.awt.Color(153, 153, 153));
        jDescricaoProj.setRows(5);
        jDescricaoProj.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIÇÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        jScrollPane4.setViewportView(jDescricaoProj);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 340, 140));

        jScrollPane8.setBorder(null);

        jOrcamentoProp.setEditable(false);
        jOrcamentoProp.setBackground(new java.awt.Color(51, 51, 51));
        jOrcamentoProp.setColumns(20);
        jOrcamentoProp.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jOrcamentoProp.setForeground(new java.awt.Color(153, 153, 153));
        jOrcamentoProp.setRows(5);
        jOrcamentoProp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ORÇAMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        jScrollPane8.setViewportView(jOrcamentoProp);

        jPanel2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 310, 140));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("PROPOSTAS ENVIADAS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 700, 10));

        jScrollPane3.setBorder(null);

        jNomeProp.setEditable(false);
        jNomeProp.setBackground(new java.awt.Color(51, 51, 51));
        jNomeProp.setColumns(20);
        jNomeProp.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jNomeProp.setForeground(new java.awt.Color(153, 153, 153));
        jNomeProp.setRows(5);
        jNomeProp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID - NOME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        jScrollPane3.setViewportView(jNomeProp);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 300, 140));

        jScrollPane9.setBorder(null);

        jDescricaoProp.setEditable(false);
        jDescricaoProp.setBackground(new java.awt.Color(51, 51, 51));
        jDescricaoProp.setColumns(20);
        jDescricaoProp.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jDescricaoProp.setForeground(new java.awt.Color(153, 153, 153));
        jDescricaoProp.setRows(5);
        jDescricaoProp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESCRIÇÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        jScrollPane9.setViewportView(jDescricaoProp);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 340, 140));

        jScrollPane12.setBorder(null);

        jOrcamentoProj.setEditable(false);
        jOrcamentoProj.setBackground(new java.awt.Color(51, 51, 51));
        jOrcamentoProj.setColumns(20);
        jOrcamentoProj.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jOrcamentoProj.setForeground(new java.awt.Color(153, 153, 153));
        jOrcamentoProj.setRows(5);
        jOrcamentoProj.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ORÇAMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        jScrollPane12.setViewportView(jOrcamentoProj);

        jPanel2.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 310, 140));

        jRemoverBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jRemoverBtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jRemoverBtn.setForeground(new java.awt.Color(153, 153, 153));
        jRemoverBtn.setText("REMOVER");
        jRemoverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoverBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jRemoverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 100, -1));

        jAntPropbtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jAntPropbtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jAntPropbtn.setForeground(new java.awt.Color(153, 153, 153));
        jAntPropbtn.setText("ANTERIOR");
        jAntPropbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAntPropbtnActionPerformed(evt);
            }
        });
        jPanel2.add(jAntPropbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 100, -1));

        jProxPropbtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jProxPropbtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jProxPropbtn.setForeground(new java.awt.Color(153, 153, 153));
        jProxPropbtn.setText("PRÓXIMO");
        jProxPropbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProxPropbtnActionPerformed(evt);
            }
        });
        jPanel2.add(jProxPropbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 100, -1));

        jProxProjbtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jProxProjbtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jProxProjbtn.setForeground(new java.awt.Color(153, 153, 153));
        jProxProjbtn.setText("PRÓXIMO");
        jProxProjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProxProjbtnActionPerformed(evt);
            }
        });
        jPanel2.add(jProxProjbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 100, -1));

        jAntProjbtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jAntProjbtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jAntProjbtn.setForeground(new java.awt.Color(153, 153, 153));
        jAntProjbtn.setText("ANTERIOR");
        jAntProjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAntProjbtnActionPerformed(evt);
            }
        });
        jPanel2.add(jAntProjbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 100, -1));

        jNProjText.setEditable(false);
        jNProjText.setBackground(new java.awt.Color(51, 51, 51));
        jNProjText.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jNProjText.setForeground(new java.awt.Color(153, 153, 153));
        jNProjText.setBorder(null);
        jPanel2.add(jNProjText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 30, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Número de Projetos:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jNPropText.setEditable(false);
        jNPropText.setBackground(new java.awt.Color(51, 51, 51));
        jNPropText.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jNPropText.setForeground(new java.awt.Color(153, 153, 153));
        jNPropText.setBorder(null);
        jPanel2.add(jNPropText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 30, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Número de Propostas:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jPerfilPropBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jPerfilPropBtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPerfilPropBtn.setForeground(new java.awt.Color(153, 153, 153));
        jPerfilPropBtn.setText("PERFIL");
        jPerfilPropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPerfilPropBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jPerfilPropBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 100, -1));

        jPerfilProjBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jPerfilProjBtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPerfilProjBtn.setForeground(new java.awt.Color(153, 153, 153));
        jPerfilProjBtn.setText("PERFIL");
        jPerfilProjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPerfilProjBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jPerfilProjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1080, 540));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("FREELANCER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("PROJETOS");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jTextField1.setPreferredSize(new java.awt.Dimension(1082, 186));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1090, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/projetosFreela.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 25));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(200, 30));

        jMenu3.setBackground(new java.awt.Color(51, 51, 51));
        jMenu3.setText("PERFIL");
        jMenu3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(95, 25));
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(51, 51, 51));
        jMenu4.setBorder(null);
        jMenu4.setText("PROJETOS");
        jMenu4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenu4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(95, 25));

        jMenuItem1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem1.setText("FREELANCER");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(115, 25));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenuItem2.setText("CLIENTE");
        jMenuItem2.setPreferredSize(new java.awt.Dimension(115, 25));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu2.setBackground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("CRIAR");
        jMenu2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(95, 25));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("BUSCAR");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(95, 25));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu5.setBackground(new java.awt.Color(51, 51, 51));
        jMenu5.setText("SAIR");
        jMenu5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(95, 25));
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRemoverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoverBtnActionPerformed
        //verifica se existe proposta
        if(!listaProp.isEmpty()){
            
            //id da proposta
            int idProp = propdao.retornaIdPropostaPelaPropostaRealizada(listaProp.get(atualProp).getPropostaRealizada());
            
            //deletando a proposta
            propdao.deletePropostaPeloId(idProp);

            //mostrando mensagem de proposta aceita
            JOptionPane.showMessageDialog(null, "Proposta deletada!");

            //atualizando a pagina
            ProjetosFreela projetosFreela = new ProjetosFreela(usuarioId);
            projetosFreela.setVisible(true);
            dispose();
        }else
            JOptionPane.showMessageDialog(null, "Ainda não há propostas realizadas!");
        
    }//GEN-LAST:event_jRemoverBtnActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        Perfil perfil = new Perfil(usuarioId);
        perfil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ProjetosFreela projetosFreela = new ProjetosFreela(usuarioId);
        projetosFreela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ProjetosCliente projetosCliente = new ProjetosCliente(usuarioId);
        projetosCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Criar criar = new Criar(usuarioId);
        criar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Buscar buscar = new Buscar(usuarioId);
        buscar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jProxProjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProxProjbtnActionPerformed
       if(tam.equals(Integer.toString(atual+1)) && !listaProj.isEmpty()){
            //seta o contador
            atual = 0;
            
            //mostra na interface
            jNomeProj.setText(listaProj.get(atual).getNomeProjeto());
            jDescricaoProj.setText(listaProj.get(atual).getDescricaoProjeto());
            jOrcamentoProj.setText("R$: "+listaProj.get(atual).getPrecoMax());
        }else if(!listaProj.isEmpty()){
            //soma o contador
            atual++;
            
            //mostra na interface
            jNomeProj.setText(listaProj.get(atual).getNomeProjeto());
            jDescricaoProj.setText(listaProj.get(atual).getDescricaoProjeto());
            jOrcamentoProj.setText("R$: "+listaProj.get(atual).getPrecoMax());
        }else{
            JOptionPane.showMessageDialog(null, "Ainda não há projetos em desenvolvimento!");
        }
    }//GEN-LAST:event_jProxProjbtnActionPerformed

    private void jAntProjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAntProjbtnActionPerformed
        if(atual==0 && !listaProj.isEmpty()){
            //seta o contador
            atual = Integer.parseInt(tam)-1;
            
            //mostra na interface
            jNomeProj.setText(listaProj.get(atual).getNomeProjeto());
            jDescricaoProj.setText(listaProj.get(atual).getDescricaoProjeto());
            jOrcamentoProj.setText("R$: "+listaProj.get(atual).getPrecoMax());
        }else if(!listaProj.isEmpty()){
            //soma o contador
            atual--;
            
            //mostra na interface
            jNomeProj.setText(listaProj.get(atual).getNomeProjeto());
            jDescricaoProj.setText(listaProj.get(atual).getDescricaoProjeto());
            jOrcamentoProj.setText("R$: "+listaProj.get(atual).getPrecoMax());
        }else{
            JOptionPane.showMessageDialog(null, "Ainda não há projetos em desenvolvimento!");
        }
    }//GEN-LAST:event_jAntProjbtnActionPerformed

    private void jAntPropbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAntPropbtnActionPerformed
        if(atualProp==0 && !listaProp.isEmpty()){
            //seta o contador
            atualProp = Integer.parseInt(tamProp)-1;
            
            //mostra na interface
            jNomeProp.setText(projdao.retornaNomePeloId(listaProp.get(atualProp).getIdProjeto()));
            jOrcamentoProp.setText("R$: "+listaProp.get(atualProp).getValorProposta());
            jDescricaoProp.setText(listaProp.get(atualProp).getPropostaRealizada());
        }else if(!listaProp.isEmpty()){
            //soma o contador
            atualProp--;
            
            //mostra na interface
            jNomeProp.setText(projdao.retornaNomePeloId(listaProp.get(atualProp).getIdProjeto()));
            jOrcamentoProp.setText("R$: "+listaProp.get(atualProp).getValorProposta());
            jDescricaoProp.setText(listaProp.get(atualProp).getPropostaRealizada());
        }else{
            JOptionPane.showMessageDialog(null, "Ainda não há propostas realizadas!");
        }
    }//GEN-LAST:event_jAntPropbtnActionPerformed

    private void jProxPropbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProxPropbtnActionPerformed
        if(tamProp.equals(Integer.toString(atualProp+1)) && !listaProp.isEmpty()){
            //seta o contador
            atualProp = 0;
  
            //mostra na interface
            jNomeProp.setText(projdao.retornaNomePeloId(listaProp.get(atualProp).getIdProjeto()));
            jOrcamentoProp.setText("R$: "+listaProp.get(atualProp).getValorProposta());
            jDescricaoProp.setText(listaProp.get(atualProp).getPropostaRealizada());
        }else if(!listaProp.isEmpty()){
            //soma o contador
            atualProp++;
            
            //mostra na interface
            jNomeProp.setText(projdao.retornaNomePeloId(listaProp.get(atualProp).getIdProjeto()));
            jOrcamentoProp.setText("R$: "+listaProp.get(atualProp).getValorProposta());
            jDescricaoProp.setText(listaProp.get(atualProp).getPropostaRealizada());
        }else{
            JOptionPane.showMessageDialog(null, "Ainda não há propostas realizadas!");
        }
    }//GEN-LAST:event_jProxPropbtnActionPerformed

    private void jPerfilPropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPerfilPropBtnActionPerformed
        //verifica se existe algum projeto
        if(!listaProp.isEmpty()){
            //id do cliente
            int cliId = listaProp.get(atual).getIdCliente();
            
            PerfilPublico perfilPublico = new PerfilPublico(cliId);
            perfilPublico.setVisible(true);
        }else if(listaProp.isEmpty()){
           JOptionPane.showMessageDialog(null, "Ainda não há propostas realizadas!");
        }
    }//GEN-LAST:event_jPerfilPropBtnActionPerformed

    private void jPerfilProjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPerfilProjBtnActionPerformed
        //verifica se existe algum projeto
        if(!listaProj.isEmpty()){
            //id do cliente
            int cliId = listaProj.get(atual).getCliente();
            
            PerfilPublico perfilPublico = new PerfilPublico(cliId);
            perfilPublico.setVisible(true);
        }else if(listaProj.isEmpty()){
           JOptionPane.showMessageDialog(null, "Ainda não há projetos cadastrados!");
        }
    }//GEN-LAST:event_jPerfilProjBtnActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetosFreela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetosFreela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetosFreela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetosFreela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetosFreela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAntProjbtn;
    private javax.swing.JButton jAntPropbtn;
    private javax.swing.JTextArea jDescricaoProj;
    private javax.swing.JTextArea jDescricaoProp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jNProjText;
    private javax.swing.JTextField jNPropText;
    private javax.swing.JTextArea jNomeProj;
    private javax.swing.JTextArea jNomeProp;
    private javax.swing.JTextArea jOrcamentoProj;
    private javax.swing.JTextArea jOrcamentoProp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jPerfilProjBtn;
    private javax.swing.JButton jPerfilPropBtn;
    private javax.swing.JButton jProxProjbtn;
    private javax.swing.JButton jProxPropbtn;
    private javax.swing.JButton jRemoverBtn;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
